import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// app/layout.tsx (Root Layout)
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuList, NavigationMenuTrigger } from "@/app/(shared)/components/ui/navigation-menu";


const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className="relative h-screen w-screen overflow-hidden">
        {/* Floating ShadCN Navigation Menu */}
        <div className="bg-gray-800 p-4 rounded-lg shadow-lg max-w-none">
          <header className="absolute top-4 left-4 right-4 z-10 w-auto">
            <NavigationMenu className="bg-gray-600 bg-opacity-50 p-4 rounded-lg shadow-lg w-full box-border">
              <NavigationMenuList className="flex justify-between w-full">
                <NavigationMenuItem>
                  <NavigationMenuTrigger>Home</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <ul>
                      <li><a href="/">Overview</a></li>
                      <li><a href="/locations">Locations</a></li>
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuTrigger>About</NavigationMenuTrigger>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuTrigger>Contact</NavigationMenuTrigger>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </header>
        </div>
        {/* Content area for MapComponent or other children */}
        <main className="absolute inset-0 overflow-hidden">
          {children} {/* MapComponent or other nested content will be rendered here */}
        </main>
      </body>
    </html>
  );
}



